---
title: "PA1_Template.Rmd"
author: "YOU!"
date: "2/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading and Pre Procesing the Data
```{r}
datafull <- read.csv(unzip("activity.zip", exdir=getwd()))
data <- na.omit(datafull)
data$date <- as.Date(data$date)
daydata <- aggregate(data$steps, by=list(date= data$date), FUN= sum)
intavgdata <- aggregate(data$steps, by=list(interval = data$interval), FUN= mean)
```

## What is mean total number of steps taken per day?

```{r}
## Total Numbers Taken Per Day
hist(daydata$x, main = paste('Steps by Day'), xlab = "Number of Steps")  

## mean and median of the total number of steps taken per day
meansteps <- mean((daydata$x))
meansteps
mediansteps <- median((daydata$x))
mediansteps
```

## What is the average daily activity pattern?
```{r}
## average number of steps taken, averaged across all days
plot(x= intavgdata$interval, y=intavgdata$x, type = "l", xlab = "Interval", ylab= "Number of Steps", main = "Average Steps by Interval")

##Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
intmax <- intavgdata[(which.max(intavgdata[,2])),1]
intmax
```

## Imputing missing values
```{r}
###Imputing missing values
TotalNA <- sum(!complete.cases(datafull))
TotalNA

### Fill in the NAs
AverageSteps <- aggregate(steps ~ interval, data = data, FUN=mean)
fillNA <- numeric()
for (i in 1:nrow(datafull)) {
  obs <- datafull[i,]
  if (is.na(obs$steps)) {
    steps <- subset(AverageSteps, interval == obs$interval)$steps
  } else {
      steps <- obs$steps
  }
  fillNA <- c(fillNA,steps)
}

### New Data set
newact <- datafull
newact$steps <- fillNA

## Histogram
TotalSteps <- aggregate (steps ~ date, data = newact, sum, na.rm=TRUE)
hist(TotalSteps$steps, main= "Total Steps Each Day", col = 'green', xlab = "Number of steps")
hist(daydata$x, main=paste("Total Steps each day"), col = 'red', xlab = "Number of steps", add=T)
legend ("topright",c("imputed", "not imputed"), col = c("green", 'red'), lwd=10)

#Mean
MeanTSteps <- mean(TotalSteps$steps)
MeanTSteps

#Median
MedianTsteps <- median(TotalSteps$steps)
MedianTsteps

#Difference
meandiff <- MeanTSteps - meansteps
meandiff
mediandiff <- MedianTsteps - mediansteps
mediandiff
```
## Are there differences in activity patterns between weekdays and weekends?

```{r}
weekdays <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")
newact$dow <- as.factor(ifelse(is.element(weekdays(as.Date(newact$date)),weekdays), "Weekday", "Weekend"))
TotalSteps <- aggregate(steps ~ interval + dow, newact, mean)
library(lattice)
xyplot(TotalSteps$steps ~ TotalSteps$interval | TotalSteps$dow, main = "Average Steps per Day by Interval", xlab= 'interval',ylab = "steps", layout= c(1,2), type = 'l')
```